# Generated by Django 5.2.4 on 2025-07-25 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regatta_id_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='senha',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
