# Generated by Django 5.2.4 on 2025-07-25 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regatta_id_app', '0002_usuario_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
    ]
