# Generated by Django 5.2.4 on 2025-07-30 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regatta_id_app', '0003_alter_usuario_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='data_admissao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
