# Generated by Django 5.2.4 on 2025-07-30 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regatta_id_app', '0004_usuario_cargo_usuario_data_admissao'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RG'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='turno_entrada',
            field=models.CharField(blank=True, choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('dia', 'Dia inteiro')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='validade_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='validade_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='visitado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
