# Generated by Django 5.2.4 on 2025-07-30 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regatta_id_app', '0005_usuario_rg_usuario_turno_entrada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
